# Generated by Django 5.2.4 on 2025-07-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0002_category_remove_vehicle_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.category'),
        ),
    ]
